[package]
name = "rustman"
version = "0.1.0"
edition = "2021"
authors = ["Daniel Bauer <bauerda@pm.me>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.10.1"
